export type Lang = 'en' | 'ru' | 'de';

export const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav-brand": "Alex Kovalov",
    "nav-about": "About",
    "nav-stack": "Stack",
    "nav-projects": "Projects",
    "nav-open-source": "Open Source",
    "nav-contact": "Contact",
    "hero-role": "Software Architect & Fullstack Developer",
    "hero-tagline": "Building scalable web applications and microservices architectures. 7 years of experience in creating robust digital solutions.",
    "btn-projects": "View Projects",
    "btn-contact": "Contact Me",
    "section-about": "About Me",
    "about-text": "I am a passionate Software Architect and Fullstack Developer with a strong focus on building efficient, scalable, and user-centric applications, including extensive experience with microservices. Throughout my 7-year career, I have successfully delivered software ranging from dynamic single-page apps to complex enterprise architectures.",
    "stats-exp": "Years Exp.",
    "stats-projects": "Projects Done",
    "section-stack": "Tech Stack",
    "section-projects": "Projects",
    "project-1-name": "E-Commerce Platform",
    "project-1-desc": "A scalable headless e-commerce backend with Next.js storefront, handling up to 10k concurrent users.",
    "project-2-name": "SaaS Analytics Dashboard",
    "project-2-desc": "Real-time interactive dashboard visualizing complex business metrics with React and WebSockets.",
    "project-3-name": "Automated Deployment Pipeline",
    "project-3-desc": "Containerized CI/CD workflow leveraging Docker and GitHub Actions, reducing deployment time by 60%.",
    "link-view": "View Project →",
    "section-github": "GitHub Projects",
    "github-1": "microservices-core-lib",
    "github-1-desc": "A foundational library for building Go microservices with tracing and auth.",
    "github-2": "react-dynamic-dashboard",
    "github-2-desc": "A customizable layout engine for React admin panels.",
    "github-3": "nestjs-auth-boilerplate",
    "github-3-desc": "Ready-to-use authentication and authorization module for NestJS.",
    "section-contact": "Get in Touch",
    "contact-desc": "Interested in working together or have a question? Feel free to reach out.",
    "label-name": "Name",
    "label-email": "Email",
    "label-message": "Message",
    "btn-send": "Send Message",
    "footer-text": "© 2026 Alex Shmidt. All rights reserved."
  },
  ru: {
    "nav-brand": "Алекс Ковалёв",
    "nav-about": "Обо мне",
    "nav-stack": "Стек",
    "nav-projects": "Проекты",
    "nav-open-source": "Open Source",
    "nav-contact": "Контакты",
    "hero-role": "Инженер-Архитектор и Fullstack Разработчик",
    "hero-tagline": "Создаю масштабируемые веб-приложения и микросервисные архитектуры. 7 лет опыта работы над надёжными цифровыми решениями.",
    "btn-projects": "Смотреть проекты",
    "btn-contact": "Связаться",
    "section-about": "Обо мне",
    "about-text": "Я инженер-архитектор и Fullstack-разработчик, специализирующийся на создании эффективных, масштабируемых веб-приложений (в том числе на микросервисах). За 7 лет работы я успешно реализовал множество проектов: от динамичных SPA до сложных корпоративных систем.",
    "stats-exp": "Лет опыта",
    "stats-projects": "Проектов",
    "section-stack": "Мой Стек",
    "section-projects": "Мои Проекты",
    "project-1-name": "E-Commerce Платформа",
    "project-1-desc": "Масштабируемый бэкенд для headless e-commerce с фронтендом на Next.js. Поддерживает 10к одновременных пользователей.",
    "project-2-name": "SaaS Дашборд Аналитики",
    "project-2-desc": "Интерактивный дашборд реального времени для визуализации бизнес-метрик с помощью React и WebSockets.",
    "project-3-name": "CI/CD Pipeline",
    "project-3-desc": "Контейнеризованный CI/CD процесс с Docker и GitHub Actions, сокративший время релиза на 60%.",
    "link-view": "Смотреть проект →",
    "section-github": "Проекты на GitHub (Open Source)",
    "github-1": "microservices-core-lib",
    "github-1-desc": "Базовая библиотека для создания микросервисов на Go с трейсингом и авторизацией.",
    "github-2": "react-dynamic-dashboard",
    "github-2-desc": "Кастомизируемый движок макетов для админ-панелей на React.",
    "github-3": "nestjs-auth-boilerplate",
    "github-3-desc": "Готовый к использованию модуль аутентификации для NestJS.",
    "section-contact": "Связаться со мной",
    "contact-desc": "Заинтересованы в сотрудничестве или есть вопросы? Напишите мне.",
    "label-name": "Имя",
    "label-email": "Email",
    "label-message": "Сообщение",
    "btn-send": "Отправить",
    "footer-text": "© 2026 Алекс Кузнецов. Права защищены."
  },
  de: {
    "nav-brand": "Alex Kovalov",
    "nav-about": "Über mich",
    "nav-stack": "Technologien",
    "nav-projects": "Projekte",
    "nav-open-source": "Open Source",
    "nav-contact": "Kontakt",
    "hero-role": "Softwarearchitekt & Fullstack Entwickler",
    "hero-tagline": "Ich entwickle skalierbare Webanwendungen und Microservices-Architekturen. 7 Jahre Erfahrung in der Erstellung robuster digitaler Lösungen.",
    "btn-projects": "Projekte ansehen",
    "btn-contact": "Kontakt aufnehmen",
    "section-about": "Über Mich",
    "about-text": "Ich bin ein Softwarearchitekt und Fullstack-Entwickler mit Fokus auf effiziente, skalierbare Anwendungen (einschließlich Microservices). In meiner 7-jährigen Karriere habe ich Software von dynamischen SPA bis hin zu komplexen Unternehmensarchitekturen erfolgreich ausgeliefert.",
    "stats-exp": "Jahre Erfahrung",
    "stats-projects": "Projekte",
    "section-stack": "Technologien",
    "section-projects": "Projekte",
    "project-1-name": "E-Commerce Plattform",
    "project-1-desc": "Ein skalierbares Headless E-Commerce-Backend mit Next.js-Frontend für bis zu 10.000 gleichzeitige Benutzer.",
    "project-2-name": "SaaS Analytics Dashboard",
    "project-2-desc": "Ein interaktives Echtzeit-Dashboard zur Visualisierung komplexer Geschäftsmetriken mit React und WebSockets.",
    "project-3-name": "CI/CD Pipeline",
    "project-3-desc": "Containerisierter CI/CD-Workflow mit Docker und GitHub Actions, der die Bereitstellungszeit um 60% reduziert.",
    "link-view": "Zum Projekt →",
    "section-github": "Open Source / GitHub Projekte",
    "github-1": "microservices-core-lib",
    "github-1-desc": "Eine grundlegende Bibliothek zum Erstellen von Go-Microservices mit Tracing und Auth.",
    "github-2": "react-dynamic-dashboard",
    "github-2-desc": "Eine anpassbare Layout-Engine für React-Admin-Panels.",
    "github-3": "nestjs-auth-boilerplate",
    "github-3-desc": "Ein einsatzbereites Authentifizierungsmodul für NestJS.",
    "section-contact": "Kontaktieren Sie mich",
    "contact-desc": "Haben Sie Interesse an einer Zusammenarbeit oder eine Frage? Melden Sie sich gerne.",
    "label-name": "Name",
    "label-email": "Email",
    "label-message": "Nachricht",
    "btn-send": "Nachricht Senden",
    "footer-text": "© 2026 Alex Shmidt. Alle Rechte vorbehalten."
  }
};